spring.application.name=hotel-booking-service

spring.datasource.url=jdbc:postgresql://hotel-booking.cf84g00a2vgp.ap-southeast-1.rds.amazonaws.com:5432/hotel_booking
spring.datasource.username=postgres
spring.datasource.password=Vuong123
spring.datasource.driver-class-name=org.postgresql.Driver

application.security.jwt.secret=rl4MPhP6MuwIJnqNSTJ+AAc3yEN34AmTP+88z5oIvxYGYQ1jTS5hZl3H7TqxR7HP
application.security.jwt.accessTokenInMinutes=360
application.security.jwt.refreshTokenInHours=24

application.cors.allowed-origins=*
application.cors.allowed-methods=*
application.cors.allowed-headers=*